version: "3.7"

networks:
  default:
    driver: bridge

services:
  portainer:
    image: portainer/portainer-ce:latest
    ports:
      - "9000:9000"
    restart: always
    volumes:
      - portainer-data:/data
      - /var/run/docker.sock:/var/run/docker.sock

  # flask:
  #   container_name: flask-app
  #   restart: always
  #   build:
  #     dockerfile: Dockerfile
  #     context: ./app/.
  #   image: flask-app-image
  #   depends_on:
  #     - magenta
  #   volumes:
  #     - ./app:/app
  #   ports:
  #     - 5000:5000 # host : docker port

  magenta:
    platform: linux/amd64
    image: xychelsea/magenta:latest-jupyter
    container_name: magenta
    restart: always
    ports:
      - "8888:8888"
    volumes:
      - ./volume/magenta:/usr/local/magenta/workspace
volumes:
  portainer-data:
